language: c

branches:
  only:
    - master

env:
  global:
    - GAPCONTAINER="gapsystem/gap-docker-stable-4.11"

  matrix:
    - REPO_URL=https://github.com/gap-packages/4ti2gap.git
    - REPO_URL=https://github.com/ffloresbrito/aaa.git
    - REPO_URL=https://github.com/gap-packages/ace.git
    - REPO_URL=https://github.com/gap-packages/aclib.git
    - REPO_URL=https://github.com/gap-packages/agt
    - REPO_URL=https://github.com/gap-packages/alnuth.git
    - REPO_URL=https://github.com/gap-packages/anupq.git
    - REPO_URL=https://github.com/gap-packages/AutoDoc.git
    - REPO_URL=https://github.com/gap-packages/automata.git
    - REPO_URL=https://github.com/gap-packages/automgrp.git
    - REPO_URL=https://github.com/gap-packages/autpgrp.git
    - REPO_URL=https://github.com/gap-packages/biogap.git
    - REPO_URL=https://github.com/gap-packages/BlissInterface.git
    - REPO_URL=https://github.com/gap-packages/CaratInterface.git
    - REPO_URL=https://github.com/homalg-project/CddInterface.git
    - REPO_URL=https://github.com/gap-packages/Char0Gauss.git
    - REPO_URL=https://github.com/gap-packages/circle.git
    - REPO_URL=https://github.com/gap-packages/cohomolo.git
    - REPO_URL=https://github.com/gap-packages/congruence.git
    - REPO_URL=https://github.com/gap-packages/corelg.git
    - REPO_URL=https://github.com/gap-packages/crime.git
    - REPO_URL=https://github.com/bh11/crisp.git
    - REPO_URL=https://github.com/gap-packages/crypting.git
    - REPO_URL=https://github.com/gap-packages/cryst.git
    - REPO_URL=https://github.com/gap-packages/crystcat.git
    - REPO_URL=https://github.com/gap-packages/cubefree.git
    - REPO_URL=https://github.com/gap-packages/curlInterface.git
    - REPO_URL=https://github.com/gap-packages/cvec.git
    - REPO_URL=https://github.com/gap-packages/datastructures.git
    - REPO_URL=https://github.com/gap-packages/debugger.git
    - REPO_URL=https://github.com/duskydolphin/DeepThoughtPackage.git
    - REPO_URL=https://github.com/gap-packages/design.git
    - REPO_URL=https://github.com/dylanpeifer/difsets.git
    - REPO_URL=https://github.com/gap-packages/Digraphs.git
    - REPO_URL=https://github.com/frankluebeck/EDIM.git
    - REPO_URL=https://github.com/gap-packages/example.git
    - REPO_URL=https://github.com/gap-packages/FactInt.git
    - REPO_URL=https://github.com/gap-packages/ferret.git
    - REPO_URL=https://github.com/chsievers/fga.git
    - REPO_URL=https://bitbucket.org/jdebeule/fining.git
    - REPO_URL=https://github.com/gap-packages/float.git
    - REPO_URL=https://github.com/gap-packages/format.git
    - REPO_URL=https://github.com/gap-packages/FPLSA.git
    - REPO_URL=https://github.com/gap-packages/fr.git
    - REPO_URL=https://github.com/gap-packages/FrancyMonoids.git
    - REPO_URL=https://github.com/nzidaric/fsr.git
    - REPO_URL=https://github.com/gap-packages/fwtree.git
    - REPO_URL=https://github.com/gap-packages/GaloisGroups.git
    - REPO_URL=https://github.com/gap-packages/gapbench.git
    - REPO_URL=https://github.com/gap-packages/GAPQuickcheck.git
    - REPO_URL=https://github.com/gap-packages/genss.git
    - REPO_URL=https://github.com/gap-packages/grape.git
    - REPO_URL=https://github.com/gap-packages/groupoids.git
    - REPO_URL=https://github.com/gap-packages/grpconst.git
    - REPO_URL=https://github.com/gap-packages/guarana.git
    - REPO_URL=https://github.com/gap-packages/guava.git
    - REPO_URL=https://github.com/gap-packages/hap.git
    - REPO_URL=https://github.com/gap-packages/hapcryst.git
    - REPO_URL=https://github.com/gap-packages/hecke.git
    - REPO_URL=https://github.com/gap-packages/HeLP.git
    - REPO_URL=https://github.com/gap-packages/idrel.git
    - REPO_URL=https://github.com/gap-packages/images.git
    - REPO_URL=https://github.com/gap-packages/img.git
    - REPO_URL=https://github.com/gap-packages/intpic.git
    - REPO_URL=https://github.com/gap-packages/io.git
    - REPO_URL=https://github.com/bh11/irredsol.git
    - REPO_URL=https://github.com/gap-packages/json.git
    - REPO_URL=https://github.com/gap-packages/JupyterKernel.git
    - REPO_URL=https://github.com/nathancarter/jupyterviz.git
    - REPO_URL=https://github.com/gap-packages/kan.git
    - REPO_URL=https://github.com/gap-packages/kbmag.git
    - REPO_URL=https://github.com/gap-packages/laguna.git
    - REPO_URL=https://github.com/gap-packages/liealgdb.git
    - REPO_URL=https://github.com/gap-packages/liepring.git
    - REPO_URL=https://github.com/gap-packages/liering.git
    - REPO_URL=https://github.com/gap-packages/LocalNR.git
    - REPO_URL=https://github.com/gap-packages/loops.git
    - REPO_URL=https://github.com/gap-packages/lpres.git
    - REPO_URL=https://github.com/MWhybrow92/MajoranaAlgebras.git
    - REPO_URL=https://github.com/gap-packages/MapClass.git
    - REPO_URL=https://github.com/hulpke/matgrp.git
    - REPO_URL=https://github.com/gap-packages/MathInTheMiddle.git
    - REPO_URL=https://github.com/gap-packages/matrixss.git
    - REPO_URL=https://github.com/gap-packages/meataxe64.git
    - REPO_URL=https://github.com/gap-packages/Memoisation.git
    - REPO_URL=https://github.com/gap-packages/modisom.git
    - REPO_URL=https://github.com/le-on/ModularGroup.git
    - REPO_URL=https://github.com/gap-packages/NautyTracesInterface.git
    - REPO_URL=https://github.com/homalg-project/NConvex.git
    - REPO_URL=https://github.com/gap-packages/nilmat.git
    - REPO_URL=https://github.com/pjastr/NoCK.git
    - REPO_URL=https://github.com/gap-packages/NormalizInterface.git
    - REPO_URL=https://github.com/gap-packages/nq.git
    - REPO_URL=https://github.com/gap-packages/numericalsgps.git
    - REPO_URL=https://github.com/gap-packages/openmath.git
    - REPO_URL=https://github.com/gap-packages/orb.git
    - REPO_URL=https://github.com/gap-packages/OrbitalGraphs.git
    - REPO_URL=https://github.com/gap-packages/PackageManager.git
    - REPO_URL=https://github.com/gap-packages/PARIInterface.git
    - REPO_URL=https://github.com/gap-packages/PatternClass.git
    - REPO_URL=https://github.com/gap-packages/permut.git
    - REPO_URL=https://github.com/gap-packages/polenta.git
    - REPO_URL=https://github.com/gap-packages/polycyclic.git
    - REPO_URL=https://github.com/gap-packages/polymaking.git
    - REPO_URL=https://github.com/FKlie/Predicata.git
    - REPO_URL=https://github.com/gap-packages/primgrp.git
    - REPO_URL=https://github.com/gap-packages/profiling.git
    - REPO_URL=https://github.com/gap-packages/qaos.git
    - REPO_URL=https://github.com/gap-packages/qpa.git
    - REPO_URL=https://github.com/oysteins/QPA2.git
    - REPO_URL=https://github.com/gap-packages/quagroup.git
    - REPO_URL=https://github.com/gap-packages/radiroot.git
    - REPO_URL=https://github.com/vlaver/RAMEGA.git
    - REPO_URL=https://github.com/gap-packages/rcwa.git
    - REPO_URL=https://github.com/gap-packages/rds.git
    - REPO_URL=https://github.com/gap-packages/recog.git
    - REPO_URL=https://github.com/gap-packages/RegisterPackageTNUMDemo.git
    - REPO_URL=https://github.com/gap-packages/RepnDecomp.git
    - REPO_URL=https://github.com/gap-packages/repsn.git
    - REPO_URL=https://github.com/gap-packages/resclasses.git
    - REPO_URL=https://github.com/gap-packages/scscp.git
    - REPO_URL=https://github.com/gap-packages/Semigroups.git
    - REPO_URL=https://github.com/gap-packages/semirings.git
    - REPO_URL=https://github.com/gap-packages/sglppow.git
    - REPO_URL=https://github.com/gap-packages/sgpdec.git
    - REPO_URL=https://github.com/gap-packages/sgpviz.git
    - REPO_URL=https://github.com/simpcomp-team/simpcomp.git
    - REPO_URL=https://github.com/gap-packages/singular.git
    - REPO_URL=https://github.com/gap-packages/SingularInterface.git
    - REPO_URL=https://github.com/gap-packages/sla.git
    - REPO_URL=https://github.com/gap-packages/smallgrp.git
    - REPO_URL=https://github.com/gap-packages/smallsemi.git
    - REPO_URL=https://github.com/gap-packages/sonata.git
    - REPO_URL=https://github.com/gap-packages/sophus.git
    - REPO_URL=https://github.com/gap-packages/spinsym.git
    - REPO_URL=https://github.com/gap-packages/subsemi.git
    - REPO_URL=https://github.com/gap-packages/SymbCompCC.git
    - REPO_URL=https://github.com/gap-packages/Thelma.git
    - REPO_URL=https://github.com/gap-packages/tomlib.git
    - REPO_URL=https://github.com/gap-packages/toric.git
    - REPO_URL=https://github.com/hulpke/transgrp.git
    - REPO_URL=https://github.com/gap-packages/unipot.git
    - REPO_URL=https://github.com/gap-packages/unitlib.git
    - REPO_URL=https://github.com/gap-packages/utils.git
    - REPO_URL=https://github.com/gap-packages/uuid.git
    - REPO_URL=https://github.com/gap-packages/walrus.git
    - REPO_URL=https://github.com/gap-packages/wedderga.git
    - REPO_URL=https://github.com/gap-packages/xmod.git
    - REPO_URL=https://github.com/gap-packages/xmodalg.git
    - REPO_URL=https://github.com/gap-packages/YangBaxter.git
    - REPO_URL=https://github.com/gap-packages/ZeroMQInterface.git

services:
  - docker

before_install:
  - docker version
  - docker pull ${GAPCONTAINER}

script:
  - docker run -v $PWD:/home/gap/travis/ ${GAPCONTAINER} /bin/sh -c "REPO_URL=${REPO_URL} TERM=xterm LANG=en_GB.UTF-8 /home/gap/travis/ci.sh"
